# example netlify.toml
[build]
  command = "npm run release"
  functions = "netlify/functions"
  publish = "build/"
[functions]
  node_bundler = "esbuild"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
